var a = `selected>&nbsp;(서울)&nbsp;-&nbsp;CORE글로벌지역학&nbsp;(COREGlobalStudies)&nbsp;</option><optionvalue="A1CE1_H1">&nbsp;(서울)&nbsp;-&nbsp;EICC학과&nbsp;(DepartmentofEnglishforInternationalConferencesandCommunication)&nbsp;</option><optionvalue="AAQ01_H1">&nbsp;(서울)&nbsp;-&nbsp;EU전공&nbsp;(EUMajor)&nbsp;</option><optionvalue="AKAA1_H1">&nbsp;(서울)&nbsp;-&nbsp;Language&Diplomacy전공&nbsp;(Language&Diplomacy)&nbsp;</option><optionvalue="AKA_H1">&nbsp;(서울)&nbsp;-&nbsp;Language&Diplomacy학부&nbsp;(DivisionofLanguage&Diplomacy)&nbsp;</option><optionvalue="A2AA1_H1">&nbsp;(서울)&nbsp;-&nbsp;Language&Trade전공&nbsp;(Language&Trade)&nbsp;</option><optionvalue="A2A_H1">&nbsp;(서울)&nbsp;-&nbsp;Language&Trade학부&nbsp;(DivisionofLanguage&Trade)&nbsp;</option><optionvalue="ALA_H1">&nbsp;(서울)&nbsp;-&nbsp;경영학부&nbsp;(BusinessAdministrationDivision)&nbsp;</option><optionvalue="ALAA1_H1">&nbsp;(서울)&nbsp;-&nbsp;경영학전공&nbsp;(BusinessAdministration)&nbsp;</option><optionvalue="AEC_H1">&nbsp;(서울)&nbsp;-&nbsp;경제학부&nbsp;(DivisionofEconomics)&nbsp;</option><optionvalue="AECA1_H1">&nbsp;(서울)&nbsp;-&nbsp;경제학전공&nbsp;(Economics)&nbsp;</option><optionvalue="ACDD1_H1">&nbsp;(서울)&nbsp;-&nbsp;광고·PR·브랜딩전공&nbsp;(Advertising·PublicRelations·Branding)&nbsp;</option><optionvalue="AFF01_H1">&nbsp;(서울)&nbsp;-&nbsp;교육학&nbsp;(Education)&nbsp;</option><optionvalue="ACAI1_H1">&nbsp;(서울)&nbsp;-&nbsp;국가리더전공&nbsp;(NationalLeader)&nbsp;</option><optionvalue="AEAA1_H1">&nbsp;(서울)&nbsp;-&nbsp;국제통상학과&nbsp;(DepartmentofInternationalEconomicsandLaw)&nbsp;</option><optionvalue="AGA_H1">&nbsp;(서울)&nbsp;-&nbsp;국제학부&nbsp;(DivisionofInternationalStudies)&nbsp;</option><optionvalue="AGAA1_H1">&nbsp;(서울)&nbsp;-&nbsp;국제학전공&nbsp;(InternationalStudies)&nbsp;</option><optionvalue="AAH01_H1">&nbsp;(서울)&nbsp;-&nbsp;네덜란드어과&nbsp;(DepartmentofDutch)&nbsp;</option><optionvalue="AAD01_H1">&nbsp;(서울)&nbsp;-&nbsp;노어과&nbsp;(DepartmentofRussian)&nbsp;</option><optionvalue="AAC01_H1">&nbsp;(서울)&nbsp;-&nbsp;독일어과&nbsp;(DepartmentofGerman)&nbsp;</option><optionvalue="AFC01_H1">&nbsp;(서울)&nbsp;-&nbsp;독일어교육과&nbsp;(DepartmentofGermanEducation)&nbsp;</option><optionvalue="ABP01_H1">&nbsp;(서울)&nbsp;-&nbsp;동북아전공&nbsp;(North-EastAsianStudiesMajor)&nbsp;</option><optionvalue="ANJA1_H1">&nbsp;(서울)&nbsp;-&nbsp;디지털인문한국학전공&nbsp;(DigitalKoreanStudiesinHumanities)&nbsp;</option><optionvalue="ABC01_H1">&nbsp;(서울)&nbsp;-&nbsp;말레이.인도네시아어과&nbsp;(DepartmentofMalay-Indonesian)&nbsp;</option><optionvalue="ABJ01_H1">&nbsp;(서울)&nbsp;-&nbsp;몽골어과&nbsp;(DepartmentofMongolian)&nbsp;</option><optionvalue="ANDD2_H1">&nbsp;(서울)&nbsp;-&nbsp;문화콘텐츠학전공&nbsp;(CulturalContentsMajor)&nbsp;</option><optionvalue="ACD_H1">&nbsp;(서울)&nbsp;-&nbsp;미디어커뮤니케이션학부&nbsp;(DivisionofMedia&Communication)&nbsp;</option><optionvalue="ACDE1_H1">&nbsp;(서울)&nbsp;-&nbsp;방송·영상·뉴미디어전공&nbsp;(Broadcasting·Film·NewMedia)&nbsp;</option><optionvalue="ADA01_H1">&nbsp;(서울)&nbsp;-&nbsp;법학과&nbsp;(DepartmentofLaw)&nbsp;</option><optionvalue="ABF01_H1">&nbsp;(서울)&nbsp;-&nbsp;베트남어과&nbsp;(DepartmentofVietnamese)&nbsp;</option><optionvalue="AAP01_H1">&nbsp;(서울)&nbsp;-&nbsp;브릭스전공&nbsp;(BRICsMajor)&nbsp;</option><optionvalue="ANDB2_H1">&nbsp;(서울)&nbsp;-&nbsp;사학과&nbsp;(DepartmentofHistory)&nbsp;</option><optionvalue="AKAB1_H1">&nbsp;(서울)&nbsp;-&nbsp;사회과학전공&nbsp;(SocialScience)&nbsp;</option><optionvalue="AANA1_H1">&nbsp;(서울)&nbsp;-&nbsp;세계문화예술경영전공&nbsp;(ArtandCulturalMediation)&nbsp;</option><optionvalue="AAI01_H1">&nbsp;(서울)&nbsp;-&nbsp;스칸디나비아어과&nbsp;(DepartmentofScandinavianLanguages)&nbsp;</option><optionvalue="AAE01_H1">&nbsp;(서울)&nbsp;-&nbsp;스페인어과&nbsp;(DepartmentofSpanish)&nbsp;</option><optionvalue="ABD01_H1">&nbsp;(서울)&nbsp;-&nbsp;아랍어과&nbsp;(DepartmentofArabic)&nbsp;</option><optionvalue="ACDA1_H1">&nbsp;(서울)&nbsp;-&nbsp;언론·정보전공&nbsp;(Journalism&Information)&nbsp;</option><optionvalue="A1CF1_H1">&nbsp;(서울)&nbsp;-&nbsp;언어와공학전공&nbsp;(LanguageandTechnology)&nbsp;</option><optionvalue="ANDC2_H1">&nbsp;(서울)&nbsp;-&nbsp;언어인지과학과&nbsp;(DepartmentofLinguisticsandCognitiveScience)&nbsp;</option><optionvalue="A1CD1_H1">&nbsp;(서울)&nbsp;-&nbsp;영미문학·문화학과&nbsp;(DepartmentofEnglishLiteratureandCulture)&nbsp;</option><optionvalue="AFA01_H1">&nbsp;(서울)&nbsp;-&nbsp;영어교육과&nbsp;(DepartmentofEnglishEducation)&nbsp;</option><optionvalue="A1BD1_H1">&nbsp;(서울)&nbsp;-&nbsp;영어전공&nbsp;(EnglishMajor)&nbsp;</option><optionvalue="A1CA1_H1">&nbsp;(서울)&nbsp;-&nbsp;영어학과&nbsp;(DepartmentofEnglishLinguistics)&nbsp;</option><optionvalue="AFH01_H1">&nbsp;(서울)&nbsp;-&nbsp;외국어로서의한국어교육전공&nbsp;(TeachingKoreanasaForeignLanguage)&nbsp;</option><optionvalue="ATMB2_H1">&nbsp;(서울)&nbsp;-&nbsp;융복합소프트웨어전공&nbsp;(SoftwareConvergenceMajor)&nbsp;</option><optionvalue="AJDA1_H1">&nbsp;(서울)&nbsp;-&nbsp;융합일본지역전공&nbsp;(IntegratedJapaneseStudies)&nbsp;</option><optionvalue="AJD_H1">&nbsp;(서울)&nbsp;-&nbsp;융합일본지역학부&nbsp;(DivisionofIntegratedJapaneseStudies)&nbsp;</option><optionvalue="ABI01_H1">&nbsp;(서울)&nbsp;-&nbsp;이란어과&nbsp;(DepartmentofPersian)&nbsp;</option><optionvalue="AAF01_H1">&nbsp;(서울)&nbsp;-&nbsp;이탈리아어과&nbsp;(DepartmentofItalian)&nbsp;</option><optionvalue="ABG01_H1">&nbsp;(서울)&nbsp;-&nbsp;인도어과&nbsp;(DepartmentofHindi)&nbsp;</option><optionvalue="AJCA1_H1">&nbsp;(서울)&nbsp;-&nbsp;일본언어문화전공&nbsp;(JapaneseLanguage,LiteratureandCulture)&nbsp;</option><optionvalue="AJC_H1">&nbsp;(서울)&nbsp;-&nbsp;일본언어문화학부&nbsp;(DivisionofJapaneseLanguage,LiteratureandCulture)&nbsp;</option><optionvalue="ACBA1_H1">&nbsp;(서울)&nbsp;-&nbsp;정치외교학과&nbsp;(DepartmentofPoliticalScienceandDiplomacy)&nbsp;</option><optionvalue="AFI01_H1">&nbsp;(서울)&nbsp;-&nbsp;중국어교육과&nbsp;(DepartmentofChineseEducation)&nbsp;</option><optionvalue="AICA1_H1">&nbsp;(서울)&nbsp;-&nbsp;중국언어문화전공&nbsp;(ChineseLanguage,LiteratureandCulture)&nbsp;</option><optionvalue="AIC_H1">&nbsp;(서울)&nbsp;-&nbsp;중국언어문화학부&nbsp;(DivisionofChineseLanguage,LiteratureandCulture)&nbsp;</option><optionvalue="AIDA1_H1">&nbsp;(서울)&nbsp;-&nbsp;중국외교통상전공&nbsp;(ChineseForeignAffairsandCommerce)&nbsp;</option><optionvalue="AID_H1">&nbsp;(서울)&nbsp;-&nbsp;중국외교통상학부&nbsp;(DivisionofChineseForeignAffairsandCommerce)&nbsp;</option><optionvalue="ANDA2_H1">&nbsp;(서울)&nbsp;-&nbsp;철학과&nbsp;(DepartmentofPhilosophy)&nbsp;</option><optionvalue="ABE01_H1">&nbsp;(서울)&nbsp;-&nbsp;태국어과&nbsp;(DepartmentofThai)&nbsp;</option><optionvalue="ABH11_H1">&nbsp;(서울)&nbsp;-&nbsp;터키.아제르바이잔어과&nbsp;(DepartmentofTurkishandAzerbaijani)&nbsp;</option><optionvalue="AAK01_H1">&nbsp;(서울)&nbsp;-&nbsp;포르투갈어과&nbsp;(DepartmentofPortuguese)&nbsp;</option><optionvalue="AAB01_H1">&nbsp;(서울)&nbsp;-&nbsp;프랑스어과&nbsp;(DepartmentofFrench)&nbsp;</option><optionvalue="AFB01_H1">&nbsp;(서울)&nbsp;-&nbsp;프랑스어교육과&nbsp;(DepartmentofFrenchEducation)&nbsp;</option><optionvalue="AAM_H1">&nbsp;(서울)&nbsp;-&nbsp;프랑스어학부&nbsp;(DivisionofFrenchLanguage)&nbsp;</option><optionvalue="AFD01_H1">&nbsp;(서울)&nbsp;-&nbsp;한국어교육과&nbsp;(DepartmentofKoreanEducation)&nbsp;</option><optionvalue="ACBB1_H1">&nbsp;(서울)&nbsp;-&nbsp;행정학과&nbsp;(DepartmentofPublicAdministration)&nbsp;</option>
`

var b = a.replace(/<optionvalue="(.+?)">&nbsp;\(서울\)&nbsp;\-&nbsp;(.+?)&nbsp;\(.+?\)&nbsp;<\/option>/g, '"$2" : "$1",\n' );


console.log(b);


`
"EICC학과" : "A1CE1_H1",
"EU전공" : "AAQ01_H1",
"Language&Diplomacy전공" : "AKAA1_H1",
"Language&Diplomacy학부" : "AKA_H1",
"Language&Trade전공" : "A2AA1_H1",
"Language&Trade학부" : "A2A_H1",
"경영학부" : "ALA_H1",
"경영학전공" : "ALAA1_H1",
"경제학부" : "AEC_H1",
"경제학전공" : "AECA1_H1",
"광고·PR·브랜딩전공" : "ACDD1_H1",
"교육학" : "AFF01_H1",
"국가리더전공" : "ACAI1_H1",
"국제통상학과" : "AEAA1_H1",
"국제학부" : "AGA_H1",
"국제학전공" : "AGAA1_H1",
"네덜란드어과" : "AAH01_H1",
"노어과" : "AAD01_H1",
"독일어과" : "AAC01_H1",
"독일어교육과" : "AFC01_H1",
"동북아전공" : "ABP01_H1",
"디지털인문한국학전공" : "ANJA1_H1",
"말레이.인도네시아어과" : "ABC01_H1",
"몽골어과" : "ABJ01_H1",
"문화콘텐츠학전공" : "ANDD2_H1",
"미디어커뮤니케이션학부" : "ACD_H1",
"방송·영상·뉴미디어전공" : "ACDE1_H1",
"법학과" : "ADA01_H1",
"베트남어과" : "ABF01_H1",
"브릭스전공" : "AAP01_H1",
"사학과" : "ANDB2_H1",
"사회과학전공" : "AKAB1_H1",
"세계문화예술경영전공" : "AANA1_H1",
"스칸디나비아어과" : "AAI01_H1",
"스페인어과" : "AAE01_H1",
"아랍어과" : "ABD01_H1",
"언론·정보전공" : "ACDA1_H1",
"언어와공학전공" : "A1CF1_H1",
"언어인지과학과" : "ANDC2_H1",
"영미문학·문화학과" : "A1CD1_H1",
"영어교육과" : "AFA01_H1",
"영어전공" : "A1BD1_H1",
"영어학과" : "A1CA1_H1",
"외국어로서의한국어교육전공" : "AFH01_H1",
"융복합소프트웨어전공" : "ATMB2_H1",
"융합일본지역전공" : "AJDA1_H1",
"융합일본지역학부" : "AJD_H1",
"이란어과" : "ABI01_H1",
"이탈리아어과" : "AAF01_H1",
"인도어과" : "ABG01_H1",
"일본언어문화전공" : "AJCA1_H1",
"일본언어문화학부" : "AJC_H1",
"정치외교학과" : "ACBA1_H1",
"중국어교육과" : "AFI01_H1",
"중국언어문화전공" : "AICA1_H1",
"중국언어문화학부" : "AIC_H1",
"중국외교통상전공" : "AIDA1_H1",
"중국외교통상학부" : "AID_H1",
"철학과" : "ANDA2_H1",
"태국어과" : "ABE01_H1",
"터키.아제르바이잔어과" : "ABH11_H1",
"포르투갈어과" : "AAK01_H1",
"프랑스어과" : "AAB01_H1",
"프랑스어교육과" : "AFB01_H1",
"프랑스어학부" : "AAM_H1",
"한국어교육과" : "AFD01_H1",
"행정학과" : "ACBB1_H1",
`